ProyectoCoder/ProyectoFinal/AppCoder/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

from AppCoder.views import (
     inicio_view, 
     crea_pais,
     crea_tipoInmueble,
     crea_arrendador,
     crea_arrendatario,
     crea_inmueble,
     Lista_inmueble,
     inmueble_buscar,
     ### CRUD
     lista_pais,
     elimina_pais,
     editar_pais,
     PaisListView,
     PaisDetail,
     PaisCreateView,
     PaisUpdateView,
     PaisDeleteView,
     PaisCreateView,
     ### LOGIN
     login_view,
     registro_view,
     ###### EDITAR USUARIO
     editar_perfil_view,
     crear_avatar_view,
     ###### ACERCA AUTOR
     acerca_autor_view,
     listar_usuarios_view,
     listar_inmuebles_view,

     )

app_name = "AppCoder"


urlpatterns = [
    path("inicio/", inicio_view, name="inicio"),
    path("Lista-inmueble/",Lista_inmueble, name="Lista-inmueble"),
    path("inmueble-buscar", inmueble_buscar, name="inmueble-buscar"),
    path("lista-pais", lista_pais, name="lista-pais"),
    ###### CRUD
    path("crea-pais/",crea_pais, name="crea-pais"),
    path("editar-pais/<int:id>",editar_pais, name="editar-pais"),
    path("elimina-pais/<int:id>",elimina_pais, name="elimina-pais"),
    path("crea-tipoinmueble/",crea_tipoInmueble, name="crea-tipoinmueble"),
    path("crea-arrendador/",crea_arrendador, name="crea-arrendador"),
    path("crea-arrendatario/",crea_arrendatario, name="crea-arrendatario"),
    path("crea-inmueble/",crea_inmueble, name="crea-inmueble"),
    ###### CBV
    path("pais_list/",PaisListView.as_view(), name="pais_list"),
    path("pais/new",PaisCreateView.as_view(), name="pais-create"),
    path("pais/<pk>",PaisDetail.as_view(), name="pais-details"),
    path("pais/<pk>/update",PaisUpdateView.as_view(), name="pais-update"),
    path("pais/<pk>/delete",PaisDeleteView.as_view(), name="pais-delete"),
    ###### LOGIN
    path("registro", registro_view, name="registro"),
    path("login", login_view, name="login"),
    path("logout", LogoutView.as_view(template_name="AppCoder/logout.html"), name="logout"),
    ###### EDITAR USUARIO
    path("editar-perfil", editar_perfil_view, name="editar-perfil"),
    path("crear-avatar", crear_avatar_view, name="crear-avatar"),
    ###### ACERCA DE MI
    path("route about/", acerca_autor_view, name="acer-auto"),
    ###### LISTADO DE USUARIO
    path("accounts/signup", listar_usuarios_view, name='listar_usuarios'),
    ###### LISTADO DE INMUEBLES
    path("route pages/",listar_inmuebles_view, name="listar_inmuebles"),

    

]

ProyectoCoder/ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("AppCoder/", include("AppCoder.urls")),

]

ProyectoCoder/ProyectoFinal/AppCoder/models.py
from django.db import models

# Create your models here.

## CLASE 24 #####################################################################
from django.contrib.auth.models import User

class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.imagen}"
#################################################################################



class Pais(models.Model):
        nombre = models.CharField(max_length=100)

        def __str__(self):
                return self.nombre
                
class Tipo_inmueble(models.Model):
        nombre = models.CharField(max_length=80, unique=True)

        def __str__(self):
                return self.nombre

class Arrendador(models.Model):
        dni = models.CharField(max_length=12) 
        nombre = models.CharField(max_length=30)
        apellido = models.CharField(max_length=30)
        email = models.EmailField()
        domicilio = models.CharField(max_length=50)


        def __str__(self):
                return f"{self.nombre} {self.apellido}"

class Arrendatario(models.Model):
        dni = models.CharField(max_length=12)
        nombre = models.CharField(max_length=30)
        apellido = models.CharField(max_length=30)
        email = models.EmailField()
        domicilio = models.CharField(max_length=50)
  

        def __str__(self):
              return f"{self.nombre} {self.apellido}"

class Inmueble(models.Model):
        nombre = models.CharField(max_length=12)
        medidas = models.CharField(max_length=20)
        precio = models.CharField(max_length=10)
        direccion = models.CharField(max_length=50)
        tipo = models.ForeignKey(Tipo_inmueble, on_delete=models.SET_NULL, null=True, blank=True)

        def __str__(self):
              return f"{self.nombre}"
        

ProyectoCoder/ProyectoFinal/AppCoder/forms.py
from django import forms
from . models import Inmueble
from . models import Pais

class PaisFormulario(forms.Form):
      nombre = forms.CharField()
  

class TipoInmuebleFormulario(forms.Form):
      nombre = forms.CharField()


class ArrendadorFormulario(forms.Form):
      dni = forms.CharField(max_length=12) 
      nombre = forms.CharField(max_length=30)
      apellido = forms.CharField(max_length=30)
      email = forms.EmailField()
      domicilio = forms.CharField(max_length=50)


class ArrendatarioFormulario(forms.Form):
      dni = forms.CharField(max_length=12) 
      nombre = forms.CharField(max_length=30)
      apellido = forms.CharField(max_length=30)
      email = forms.EmailField()
      domicilio = forms.CharField(max_length=50)

class InmuebleFormulario(forms.ModelForm):
      # nombre = forms.CharField(max_length=12)
      # medidas = forms.CharField(max_length=20)
      # precio = forms.CharField(max_length=10)
      # direccion = forms.CharField(max_length=50)
      # tipo_id = forms.IntegerField()     

      class Meta:
            model=Inmueble
            fields="__all__"

      # def __init__(self, *args, **kwargs):
      #       super(InmuebleFormulario, self).__init__(*args, **kwargs)
      #       self.fields['tipo'].queryset = Inmueble.objects.all()


class InmuebleBuscarFormulario(forms.Form):
      nombre = forms.CharField()
     #medidas = forms.CharField()


#### CLASE 23: registro

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UserModel
from .models import Avatar


class UserCreationFormulario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = UserModel
        fields = ["password1", "password2", "username", "email"]
        help_texts = {k: "" for k in fields}


class UserEditionFormulario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")

    class Meta:
        model = UserModel
        fields = ["email", "password1", "password2", "first_name", "last_name"]
        help_texts = {k: "" for k in fields}


class UserAvatarFormulario(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ["imagen"]

ProyectoCoder/ProyectoFinal/AppCoder/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from . import models
from .models import Pais, Tipo_inmueble, Arrendador, Arrendatario, Inmueble, Avatar

from .forms import PaisFormulario, TipoInmuebleFormulario, ArrendadorFormulario, ArrendatarioFormulario, InmuebleFormulario, InmuebleBuscarFormulario

# Create your views here.

from django.http import HttpResponse

from django.contrib.auth.decorators import login_required


def inicio_view(request):
#   return render(request, "AppCoder/inicio.html")
    if request.user.is_authenticated:
        usuario = request.user
        avatar = Avatar.objects.filter(user=usuario).last()
        avatar_url = avatar.imagen.url if avatar is not None else ""
    else:
        avatar_url = ""

    return render(request, "AppCoder/inicio.html", context={"avatar_url": avatar_url})

# def view_inicio(xx):
#     #return HttpResponse("Bienvenidos ...!!!")
#      return render(xx, "AppCoder/padre.html")


#******************************************************************
#****************    CREACION DE REGISTROS   **********************
#******************************************************************
@login_required
def crea_tipoInmueble(request):

    if request.method == "POST":
      
        miFormulario = TipoInmuebleFormulario(request.POST)
    
        if miFormulario.is_valid():
           data = miFormulario.cleaned_data
           tipoinmueble = Tipo_inmueble(nombre=data["nombre"])
           tipoinmueble.save()
           return redirect('AppCoder:inicio')
        
        return render(request, "AppCoder/tipoinmuebleFormulario.html",{"miFormulario":miFormulario})
    
    else:

        miFormulario = TipoInmuebleFormulario()

        return render(request, "AppCoder/tipoinmuebleFormulario.html",{"miFormulario":miFormulario})

@login_required
def crea_arrendador(request):

    if request.method == "POST":
      
        miFormulario = ArrendadorFormulario(request.POST)
    
        if miFormulario.is_valid():
           data = miFormulario.cleaned_data
           arrendador = Arrendador(dni=data["dni"], nombre=data["nombre"], apellido=data["apellido"], email=data["email"],domicilio=data["domicilio"] )
           arrendador.save()
           return redirect('AppCoder:inicio')
        
        return render(request, "AppCoder/arrendadorFormulario.html",{"miFormulario":miFormulario})
    
    else:
       
        miFormulario = ArrendadorFormulario()

        return render(request, "AppCoder/arrendadorFormulario.html",{"miFormulario":miFormulario})


@login_required
def crea_arrendatario(request):

    if request.method == "POST":
      
        miFormulario = ArrendatarioFormulario(request.POST)
    
        if miFormulario.is_valid():
           data = miFormulario.cleaned_data
           arrendatario = Arrendatario(dni=data["dni"], nombre=data["nombre"], apellido=data["apellido"], email=data["email"],domicilio=data["domicilio"] )
           arrendatario.save()
           return redirect('AppCoder:inicio')
        
        return render(request, "AppCoder/arrendatarioFormulario.html",{"miFormulario":miFormulario})
    
    else:
        
        miFormulario = ArrendadorFormulario()

        return render(request, "AppCoder/arrendatarioFormulario.html",{"miFormulario":miFormulario})

@login_required
def crea_inmueble(request):

    if request.method == "POST":
      
        miFormulario = InmuebleFormulario(request.POST)
    
        if miFormulario.is_valid():
           data = miFormulario.cleaned_data
           inmueble = Inmueble(nombre=data["nombre"], medidas=data["medidas"], precio=data["precio"],direccion=data["direccion"], tipo=data["tipo"])
           inmueble.save()
           return redirect('AppCoder:inicio')
        
        return render(request, "AppCoder/inmuebleFormulario.html",{"miFormulario":miFormulario})
    
    else:
        
        miFormulario = InmuebleFormulario()

        return render(request, "AppCoder/inmuebleFormulario.html",{"miFormulario":miFormulario})

#******************************************************************
#*****************    LISTADO DE ENTIDADES   **********************
#******************************************************************

def Lista_inmueble(request):
    
    inmueble = Inmueble.objects.all()

    return render(request,"AppCoder/inmueblelistado.html", {"inmueble":inmueble})


# def Lista_inmueble(request):
#     todos_los_inmuebles = []
#     for inmueble in Inmueble.objects.all():
#         todos_los_inmuebles.append(inmueble)

#     contexto = {"inmueble": todos_los_inmuebles}
#     return render(request, "AppCoder/inmueblelistado.html", contexto)

#******************************************************************
#*****************    BUSQEDA DE INMUEBLE    **********************
#******************************************************************

def inmueble_buscar(request):
    if request.method == "GET":
        form = InmuebleBuscarFormulario()
        return render(
            request,
            "AppCoder/inmuebleBuscaFormulario.html",
            context={"form":form}
        )
    else:
        formulario = InmuebleBuscarFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            inmueble_filtrados = []
            for inmueblex in Inmueble.objects.filter(nombre=informacion["nombre"]):
                inmueble_filtrados.append(inmueblex)

            contexto = {"inmueble": inmueble_filtrados}
            return render(request, "AppCoder/inmueblelistado.html", contexto)


#******************************************************************
#********************      CRUD FUNCIONAL      ********************
#******************************************************************
        
######################## CREA PAIS  ########################
@login_required        
def lista_pais(request):

    pais = Pais.objects.all()

    return render(request,"AppCoder/paislistado.html", {"pais":pais})

######################## LISTA PAIS  ########################
@login_required
def crea_pais(request):

    if request.method == "POST":
      
        miFormulario = PaisFormulario(request.POST)
    
        if miFormulario.is_valid():
           data = miFormulario.cleaned_data
           pais = Pais(nombre=data["nombre"])
           pais.save()
           return redirect('AppCoder:inicio')
        
        return render(request, "AppCoder/paisFormulario.html",{"miFormulario":miFormulario})
    
    else:
      
        miFormulario = PaisFormulario()

        return render(request, "AppCoder/PaisFormulario.html",{"miFormulario":miFormulario})

######################## ACTULAIZA PAIS  ########################
@login_required
def editar_pais(req, id):

    if req.method == "POST":
      
        miFormulario = PaisFormulario(req.POST)
    
        if miFormulario.is_valid():
           data = miFormulario.cleaned_data
           pais = Pais.objects.get(id=id)
          
           pais.nombre = data["nombre"]
           pais.save()
           return redirect('AppCoder:inicio')
        
        return render(req, "AppCoder/editarpais.html",{"miFormulario":miFormulario})
    
    else:
           pais = Pais.objects.get(id=id)
           
           miFormulario = PaisFormulario(initial={"nombre":pais.nombre})

           return render(req, "AppCoder/editarpais.html",{"miFormulario":miFormulario, "id":pais.id})
  
######################## ELIMINA PAIS  ########################
@login_required
def elimina_pais(req, id):

    if req.method == "POST":
        pais = Pais.objects.get(id=id) 
        pais.delete()

        pais = Pais.objects.all()

        return render(req,"AppCoder/paislistado.html", {"pais":pais})


#*************************************************************************
#*****************   "CRUD" Con vistas basadas en Clases  ****************
#*************************************************************************
#*******
#*** Pais CRUD create read update y delete
#*******

from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


class PaisListView(LoginRequiredMixin, ListView):
    model = Pais
    template_name = 'AppCoder/cbv_pais_list.html'
    context_object_name = "pais"   

class PaisDetail(LoginRequiredMixin,DeleteView):
    model = Pais
    template_name = 'AppCoder/Pais_detail.html'
    context_object_name = "pais"   

class PaisCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Pais
    template_name = 'AppCoder/cbv_pais_create.html'
    success_url = reverse_lazy("AppCoder:pais_list") 
    fields = ["nombre"]

class PaisUpdateView(LoginRequiredMixin,UpdateView):
    model = Pais
    template_name = 'AppCoder/cbv_pais_update.html'
    success_url = reverse_lazy("AppCoder:pais_list") 
    fields = ["nombre"]
     

class PaisDeleteView(LoginRequiredMixin,DeleteView):
    model = Pais
    template_name = 'AppCoder/cbv_pais_delete.html'
    success_url = reverse_lazy("AppCoder:pais_list")


#################### CLASE 23:  Login / Logout #########################################
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate

def login_view(request):

    if request.user.is_authenticated:
        return render(
            request,
            "AppCoder/inicio.html",
            {"mensaje": f"Ya estás autenticado: {request.user.username}"}
        )

    if request.method == "GET":
        return render(
            request,
            "AppCoder/login.html",
            {"form": AuthenticationForm()}
        )
    else:
        formulario = AuthenticationForm(request, data=request.POST)

        if formulario.is_valid():
            informacion = formulario.cleaned_data

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/arrendadorFormulario.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
    <body style="background-color: green;">
        <h5>Registro de Arrendador:</h5>
        <form action="{% url 'AppCoder:crea-arrendador' %}" method="POST">{% csrf_token %}
            {{ miFormulario.as_p }}
            <input type="submit" value="Guardar">
        </form>
    </body>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/arrendatarioFormulario.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
    <body style="background-color: green;">
        <form action="{% url 'AppCoder:crea-arrendatario' %}" method="POST">{% csrf_token %}
            {{ miFormulario.as_p }}
            <input type="submit" value="Guardar">
        </form>
    </body>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/cbv_pais_update.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia%}
<!DOCTYPE html>
 <html lang="en">

 <head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Editar Pais</title>
 </head>

 <body style="background-color: green;">
     <form action="{% url 'AppCoder:pais-update' pais.pk %}" method="POST">
         {% csrf_token %}
         {{ form.as_p }}
         <input type="submit" value="Editar">
     </form>
 </body>

 </html>
{% endblock%}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/editar_perfil.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia%}
<!DOCTYPE html>
 <html lang="en">

 <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4; max-width: 600px; margin: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">

    <h6 style="color: #4a90e2; border-bottom: 2px solid #4a90e2; padding-bottom: 10px;">
        Editar usuario: {{ usuario }}
    </h6>

    <div style="margin-top: 20px; background-color: white; padding: 20px; border-radius: 5px;">
        <form action="/AppCoder/editar-perfil" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Guardar" style="background-color: #4a90e2; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
        </form>
    </div>

</div>
{% endblock%}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/editarpais.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
    <body style="background-color: green;">
        <h5>Editar Pais:</h5>
        <form action="{% url 'AppCoder:editar-pais' id %}" method="POST">{% csrf_token %}
            {{ miFormulario.as_p }}
            <input type="submit" value="Grabar">
        </form>
    </body>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/inicio.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
   Bienvenidos a mi web...!!!!!
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/inmuebleFormulario.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
    <body>
        <h5>Registro de Inmueble:</h5>
        <form action="{% url 'AppCoder:crea-inmueble' %}" method="POST">{% csrf_token %}
            {{ miFormulario.as_p }}
            <input type="submit" value="Guardar">
        </form>
    </body>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/inmueblelistado.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
Aquí va la listado de Inmuebles o una busqueda especifica...!!!


{% if inmueble %}
<ul>
    {% for inmueblex in inmueble %}
    <li>{{ inmueblex.nombre }} {{ inmueblex.medidas }} {{ inmueblex.precio }} {{ inmueblex.direccion }} </li>
    {% endfor %}
</ul>
{% else %}
<H1>No existen inmuebles en la BBDD ...!!!</H1>
{% endif %}


{% endblock %}

 

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/logout.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia%}
<h2>Te has deslogeado</h2>
{% endblock%}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/paisFormulario.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
    <body style="background-color: green;">
        <h5>Registro de Pais:</h5>
        <form action="{% url 'AppCoder:crea-pais' %}" method="POST">{% csrf_token %}
            {{ miFormulario.as_p }}
            <input type="submit" value="Guardar">
        </form>
    </body>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/pais_list.html
{% extends "AppCoder/padre.html" %}

{% block contenidoQueCambia %}
<style>
    .content-container {
        text-align: center;
        margin-top: 40px;
    }

    .content-container h2 {
        color: #4CAF50;
        margin-bottom: 20px;
    }

    ul {
        list-style: none;
        padding: 0;
    }

    li {
        background-color: #f2f2f2;
        margin: 10px auto;
        padding: 15px;
        border-radius: 10px;
        width: 50%;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease;
    }

    li:hover {
        background-color: #e8e8e8;
        box-shadow: 0 6px 8px rgba(0, 0, 0, 0.15);
    }
</style>

<div class="content-container">
    <h2>Aquí va la lista de paises!</h2>

    {% if pais %}
    <ul>
        {% for paisx in pais %}
        <li>{{ paisx.nombre }} </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No hay paises disponibles.</p>
    {% endif %}
</div>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/paislistado.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
Aquí va listado de Paises ...!!!


{% if pais %}
<ul>
    {% for paisx in pais %}
    <li>{{ paisx.nombre }} </li>
    <div>
        <form action="{% url "AppCoder:elimina-pais" paisx.id %}" method="POST">{% csrf_token %}
            <button type="submit">Eliminar</button>
        </form>
        
        <button>
            <a href="{% url 'AppCoder:editar-pais' paisx.id %}">Editar</a>  
        </button>
    </div>
    {% endfor %}
</ul> 
{% else %}
<H1>No existe pais en la BBDD ...!!!</H1>
{% endif %}

{% endblock %}
  

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/registro.html
{% extends 'AppCoder/padre.html' %}

{% block contenidoQueCambia %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <style>
        .error-list {
            color: red;
        }
    </style>
</head>

<body style="background-color: rgb(227, 224, 225);">
<h2>Registro</h2>
<form action="/AppCoder/registro" method="POST">
    {% csrf_token %}

    {% for field in form %}
        <p>
            {{ field.label_tag }}
            {{ field }}

            {% if field.errors %}
                <ul class="error-list">
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </p>
    {% endfor %}

    <input type="submit" value="Iniciar sesión">
</form>
</body>
</html>
{% endblock %}

ProyectoCoder/ProyectoFinal/AppCoder/templates/AppCoder/tipoinmuebleFormulario.html
{% extends "AppCoder/padre.html" %}


{% block contenidoQueCambia %}
    <body style="background-color: green;">
        <h5>Registro Tipo de Inmueble:</h5>
        <form action="{% url 'AppCoder:crea-tipoinmueble' %}" method="POST">{% csrf_token %}
            {{ miFormulario.as_p }}
            <input type="submit" value="Guardar">
        </form>
    </body>
{% endblock %}